# Generated by Django 5.1.2 on 2024-10-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('price', models.IntegerField()),
                ('is_multiple_bed', models.BooleanField()),
                ('check_in_date', models.DateTimeField()),
                ('check_out_date', models.DateTimeField()),
            ],
        ),
    ]
