# Generated by Django 5.1.2 on 2024-10-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rooms', '0003_alter_room_check_in_date_alter_room_check_out_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image_relative_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
